### PR TITLE
Changed Navigation

### PR DESCRIPTION
**Pull request by Cyborgnetical**
Made a few changes to the navigation. Turned it into a table and the selected page is now bold. No css added.

### CODE REVIEW

**Comment by Cyborgnetical** [comment]
I don't think he will be back ;-;

**Comment by Cyborgnetical** [comment]
Added a config using git actions to deploy to gitpages, Please do merge. I really like this repo.

**Comment by Cyborgnetical** [comment]
welp, its ded

**Comment by Cyborgnetical** [comment]
Ima close it

**Comment by Cheng57** [comment]
Hi,

I am sorry to get back to you late.
I just had a holiday and I couldn't access emails during the moment. I am
glad that you are trying to improve the code. Could you please reopen the
pull request? Thanks!

Best,
Cheng

**Pull request closed without merging**
